apiVersion: apps/v1
kind: Deployment
metadata:
  name: irecruit-web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: irecruit-web
  template:
    metadata:
      labels:
        app: irecruit-web
    spec:
      containers:
        - name: web
          image: irecruit-web:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: irecruit-web-config
            - secretRef:
                name: irecruit-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: irecruit-web
spec:
  selector:
    app: irecruit-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30040
  type: NodePort
